export type ReviewChoice = {
  value: string;
  label: string;
};

export type ReviewStepCopy = {
  title: string;
  helper: string;
  question?: string;
};

export type SystemReviewCopy = {
  direction: "rtl" | "ltr";
  pageBadge: string;
  pageTitle: string;
  pageSubtitle: string;
  brandSignature: string;
  progressText: string;
  next: string;
  previous: string;
  submit: string;
  sending: string;
  optional: string;
  privacyNote: string;
  validationRequired: string;
  validationEmail: string;
  validationOther: string;
  validationConsent: string;
  submitError: string;
  successTitle: string;
  successBody: string;
  backHome: string;
  consent: string;
  fields: {
    name: string;
    businessName: string;
    email: string;
    website: string;
    other: string;
    workflowNotes: string;
    mainProblem: string;
    sensitiveNotes: string;
    finalNotes: string;
    budget: string;
    timeline: string;
  };
  placeholders: {
    name: string;
    businessName: string;
    email: string;
    website: string;
    businessOther: string;
    workflowNotes: string;
    mainProblem: string;
    systemOther: string;
    sensitiveNotes: string;
    finalNotes: string;
  };
  steps: ReviewStepCopy[];
  businessTypes: ReviewChoice[];
  workflowOptions: ReviewChoice[];
  systemOptions: ReviewChoice[];
  customerOptions: ReviewChoice[];
  adminOptions: ReviewChoice[];
  sensitiveOptions: ReviewChoice[];
  budgetOptions: ReviewChoice[];
  timelineOptions: ReviewChoice[];
  sensitiveHelper: string;
};

const commonSocial = [
  { value: "instagram-dm", label: "Instagram DM" },
  { value: "whatsapp", label: "WhatsApp" },
];

export const systemReviewCopy: Record<string, SystemReviewCopy> = {
  en: {
    direction: "ltr",
    pageBadge: "System Review Request",
    pageTitle: "Start a System Review",
    pageSubtitle: "Answer a few guided questions so we can understand your business, workflow and the system you need.",
    brandSignature: "From Idea to System",
    progressText: "Step {{step}} of {{total}}",
    next: "Next",
    previous: "Previous",
    submit: "Send System Review Request",
    sending: "Sending request...",
    optional: "Optional",
    privacyNote: "Your answers are used only to review the project and recommend the right next step.",
    validationRequired: "Please answer the required fields before continuing.",
    validationEmail: "Please enter a valid work email.",
    validationOther: "Please add a short note for “Other”.",
    validationConsent: "Please confirm the final checkbox before sending.",
    submitError: "The request could not be sent right now. Please try again in a moment.",
    successTitle: "Your request has been sent.",
    successBody: "We will review your answers and, if the project is a good fit, contact you to arrange a System Review session.",
    backHome: "Back to Home",
    consent: "I understand this form is for an initial project review and that, if the project is a good fit, I will be contacted to arrange a System Review session.",
    fields: {
      name: "Your name",
      businessName: "Business name",
      email: "Work email",
      website: "Current website or Instagram link",
      other: "Please explain",
      workflowNotes: "Briefly describe the current workflow",
      mainProblem: "Main problem",
      sensitiveNotes: "What kind of information or files are stored?",
      finalNotes: "Anything else we should know?",
      budget: "Approximate budget",
      timeline: "Ideal timeline",
    },
    placeholders: {
      name: "e.g. Sara Ahmadi",
      businessName: "e.g. Aura Clinic",
      email: "name@company.com",
      website: "https://... or @yourpage",
      businessOther: "Tell us what type of business it is",
      workflowNotes: "A short explanation is enough.",
      mainProblem: "For example: bookings are scattered, payments are separate, customers ask for too many updates, data lives in too many places, or the team cannot manage everything from one panel.",
      systemOther: "What else should the system include?",
      sensitiveNotes: "For example: customer photos, medical notes, private files, invoices or ID documents.",
      finalNotes: "Share anything about the idea, current tools, similar systems, files or the product you want built.",
    },
    steps: [
      { title: "First, let’s understand your business", helper: "We need a few basic details so we can review the project properly." },
      { title: "What type of business do you run?", helper: "Choose the option closest to your work." },
      { title: "How does the work happen now?", helper: "Where do customers contact you, book or place orders today?", question: "Select every channel or tool that is currently part of the workflow." },
      { title: "What is the biggest problem right now?", helper: "If one part of the workflow should improve first, what would it be?", question: "Describe the main issue in your own words." },
      { title: "What should the system include?", helper: "Choose the parts that matter for your system." },
      { title: "What should customers be able to do?", helper: "Think about the customer experience inside the system." },
      { title: "What does your team need in the admin panel?", helper: "Choose what you or your team need to manage day to day." },
      { title: "Will the system store sensitive data or private files?", helper: "This helps us review access, security and data ownership properly." },
      { title: "Approximate budget and timeline", helper: "A rough range is enough for the first review." },
      { title: "Anything else we should know?", helper: "Add any extra context before sending the request." },
    ],
    businessTypes: [
      { value: "beauty-health-clinic", label: "Beauty / health clinic" },
      { value: "dental-medical", label: "Dental / medical clinic" },
      { value: "print-advertising", label: "Print and advertising" },
      { value: "salon-nails-hair", label: "Salon / nails / hair" },
      { value: "coach-consultant", label: "Coach / consultant / personal service" },
      { value: "shop-boutique", label: "Shop / boutique" },
      { value: "restaurant-cafe", label: "Restaurant / cafe" },
      { value: "online-business", label: "Online business" },
      { value: "saas-idea", label: "SaaS idea or product" },
      { value: "other", label: "Other" },
    ],
    workflowOptions: [
      ...commonSocial,
      { value: "phone", label: "Phone calls" },
      { value: "website-form", label: "Website form" },
      { value: "sheets", label: "Google Sheets / Excel" },
      { value: "in-person", label: "In person" },
      { value: "current-booking", label: "Current booking system" },
      { value: "current-crm", label: "Current CRM" },
      { value: "other", label: "Other" },
    ],
    systemOptions: [
      { value: "online-booking", label: "Online booking" },
      { value: "online-payment", label: "Online payment" },
      { value: "admin-dashboard", label: "Admin dashboard" },
      { value: "customer-panel", label: "Customer panel" },
      { value: "crm", label: "CRM / customer management" },
      { value: "online-ordering", label: "Online ordering" },
      { value: "file-upload", label: "File upload" },
      { value: "auto-messages", label: "Automated SMS and email" },
      { value: "status-tracking", label: "Order or booking status" },
      { value: "reporting", label: "Reporting" },
      { value: "roles", label: "Different user roles" },
      { value: "ai", label: "AI" },
      { value: "automation", label: "Automation" },
      { value: "other", label: "Other" },
    ],
    customerOptions: [
      { value: "signup-login", label: "Sign up / log in" },
      { value: "book-appointment", label: "Book an appointment" },
      { value: "pay", label: "Pay" },
      { value: "view-status", label: "View booking or order status" },
      { value: "history", label: "View past sessions or orders" },
      { value: "upload-file", label: "Upload a file" },
      { value: "receive-message", label: "Receive SMS or email" },
      { value: "download-file", label: "Download output or files" },
      { value: "send-request", label: "Send a request or note" },
      { value: "not-sure", label: "Not sure yet" },
    ],
    adminOptions: [
      { value: "view-bookings", label: "View bookings" },
      { value: "manage-schedule", label: "Manage schedule" },
      { value: "manage-orders", label: "Manage orders" },
      { value: "manage-customers", label: "Manage customers" },
      { value: "manage-payments", label: "Manage payments" },
      { value: "change-status", label: "Change statuses" },
      { value: "files", label: "Upload or view files" },
      { value: "internal-notes", label: "Internal notes" },
      { value: "revenue-report", label: "Revenue reporting" },
      { value: "manage-services", label: "Manage services" },
      { value: "team-roles", label: "Manage staff or roles" },
      { value: "access-levels", label: "Different access levels" },
      { value: "not-sure", label: "Not sure yet" },
    ],
    sensitiveOptions: [
      { value: "normal", label: "No, only normal customer information" },
      { value: "private-files", label: "Yes, customer files or photos are stored" },
      { value: "medical", label: "Yes, medical or sensitive information exists" },
      { value: "not-sure", label: "Not sure" },
    ],
    budgetOptions: [
      { value: "under-750", label: "Under £750" },
      { value: "750-1500", label: "£750 to £1,500" },
      { value: "1500-3000", label: "£1,500 to £3,000" },
      { value: "3000-plus", label: "£3,000+" },
      { value: "not-sure", label: "Not sure yet" },
    ],
    timelineOptions: [
      { value: "asap", label: "As soon as possible" },
      { value: "2-4-weeks", label: "2 to 4 weeks" },
      { value: "1-2-months", label: "1 to 2 months" },
      { value: "2-plus-months", label: "More than 2 months" },
      { value: "not-sure", label: "Not sure yet" },
    ],
    sensitiveHelper: "If sensitive or medical data is involved, the proposal will include a separate review of security, access levels and data ownership.",
  },
  fa: {
    direction: "rtl",
    pageBadge: "درخواست بررسی سیستم",
    pageTitle: "شروع بررسی سیستم",
    pageSubtitle: "چند سؤال کوتاه را مرحله‌به‌مرحله پاسخ دهید تا کسب‌وکار، مسیر فعلی و سیستمی که نیاز دارید را درست بررسی کنیم.",
    brandSignature: "از ایده تا سیستم",
    progressText: "مرحله {{step}} از {{total}}",
    next: "بعدی",
    previous: "قبلی",
    submit: "ارسال درخواست بررسی سیستم",
    sending: "در حال ارسال درخواست...",
    optional: "اختیاری",
    privacyNote: "اطلاعات شما فقط برای بررسی پروژه و پیشنهاد قدم بعدی استفاده می‌شود.",
    validationRequired: "برای ادامه، فیلدهای ضروری این مرحله را کامل کنید.",
    validationEmail: "لطفاً یک ایمیل کاری معتبر وارد کنید.",
    validationOther: "لطفاً گزینه «سایر» را کوتاه توضیح دهید.",
    validationConsent: "برای ارسال درخواست، تأیید نهایی را فعال کنید.",
    submitError: "در حال حاضر ارسال درخواست انجام نشد. لطفاً چند لحظه دیگر دوباره امتحان کنید.",
    successTitle: "درخواست شما ارسال شد.",
    successBody: "ما اطلاعات شما را بررسی می‌کنیم و در صورت مناسب بودن پروژه، برای هماهنگی جلسه System Review با شما تماس می‌گیریم.",
    backHome: "بازگشت به صفحه اصلی",
    consent: "متوجه هستم که این فرم برای بررسی اولیه پروژه است و پس از بررسی، در صورت مناسب بودن پروژه، برای جلسه System Review با من تماس گرفته می‌شود.",
    fields: {
      name: "نام شما",
      businessName: "نام کسب‌وکار",
      email: "ایمیل کاری",
      website: "وب‌سایت یا لینک اینستاگرام فعلی",
      other: "لطفاً توضیح دهید",
      workflowNotes: "اگر لازم است، مسیر فعلی کار را کوتاه توضیح دهید",
      mainProblem: "بزرگ‌ترین مشکل فعلی",
      sensitiveNotes: "چه نوع اطلاعات یا فایل‌هایی ذخیره می‌شوند؟",
      finalNotes: "چیزی هست که باید بدانیم؟",
      budget: "بودجه تقریبی",
      timeline: "زمان‌بندی تقریبی",
    },
    placeholders: {
      name: "مثلاً سارا احمدی",
      businessName: "مثلاً کلینیک آورا",
      email: "name@company.com",
      website: "https://... یا yourpage@",
      businessOther: "کوتاه توضیح دهید چه نوع کسب‌وکاری دارید",
      workflowNotes: "چند خط کوتاه کافی است.",
      mainProblem: "مثلاً رزروها پراکنده‌اند، پرداخت‌ها جداست، مشتری‌ها زیاد پیگیری می‌پرسند، اطلاعات در چند جا پخش شده، یا تیم نمی‌تواند همه چیز را از یک پنل مدیریت کند.",
      systemOther: "چه قابلیت دیگری باید داخل سیستم باشد؟",
      sensitiveNotes: "مثلاً عکس مشتری، پرونده پزشکی، فایل خصوصی، فاکتور یا مدارک هویتی.",
      finalNotes: "هر توضیحی درباره ایده، مشکل، ابزارهای فعلی، فایل‌ها، سیستم‌های مشابه یا چیزی که دوست دارید ساخته شود.",
    },
    steps: [
      { title: "اول با کسب‌وکار شما آشنا شویم", helper: "برای اینکه بتوانیم پروژه را بهتر بررسی کنیم، اول چند اطلاعات پایه نیاز داریم." },
      { title: "کسب‌وکار شما در چه زمینه‌ای فعالیت می‌کند؟", helper: "گزینه‌ای را انتخاب کنید که به کار شما نزدیک‌تر است." },
      { title: "الان کارها چطور انجام می‌شوند؟", helper: "مشتری‌ها الان چطور با شما تماس می‌گیرند، رزرو می‌کنند یا سفارش می‌دهند؟", question: "هر کانال یا ابزاری که الان در مسیر کار شما هست انتخاب کنید." },
      { title: "بزرگ‌ترین مشکل فعلی چیست؟", helper: "اگر فقط یک بخش از کارتان قرار باشد بهتر شود، آن بخش چیست؟", question: "مشکل اصلی را با زبان خودتان بنویسید." },
      { title: "چه چیزهایی برای سیستم شما مهم است؟", helper: "قابلیت‌هایی را انتخاب کنید که برای سیستم شما مهم هستند." },
      { title: "مشتری داخل سیستم باید چه کاری بتواند انجام دهد؟", helper: "به تجربه مشتری داخل سیستم فکر کنید." },
      { title: "شما یا تیم‌تان داخل پنل مدیریت چه چیزی نیاز دارید؟", helper: "مواردی را انتخاب کنید که برای مدیریت روزانه لازم دارید." },
      { title: "آیا سیستم اطلاعات حساس یا فایل خصوصی ذخیره می‌کند؟", helper: "این موضوع برای بررسی امنیت، دسترسی‌ها و مالکیت داده مهم است." },
      { title: "بودجه و زمان‌بندی تقریبی", helper: "یک بازه تقریبی برای بررسی اولیه کافی است." },
      { title: "چیزی هست که باید بدانیم؟", helper: "اگر توضیح دیگری دارید، قبل از ارسال اضافه کنید." },
    ],
    businessTypes: [
      { value: "beauty-health-clinic", label: "کلینیک زیبایی / سلامت" },
      { value: "dental-medical", label: "دندان‌پزشکی / کلینیک پزشکی" },
      { value: "print-advertising", label: "چاپ و تبلیغات" },
      { value: "salon-nails-hair", label: "سالن زیبایی / ناخن / مو" },
      { value: "coach-consultant", label: "مربی / مشاور / خدمات شخصی" },
      { value: "shop-boutique", label: "فروشگاه / بوتیک" },
      { value: "restaurant-cafe", label: "رستوران / کافه" },
      { value: "online-business", label: "کسب‌وکار آنلاین" },
      { value: "saas-idea", label: "ایده یا محصول SaaS" },
      { value: "other", label: "سایر" },
    ],
    workflowOptions: [
      ...commonSocial,
      { value: "phone", label: "تماس تلفنی" },
      { value: "website-form", label: "فرم سایت" },
      { value: "sheets", label: "Google Sheets / Excel" },
      { value: "in-person", label: "حضوری" },
      { value: "current-booking", label: "سیستم رزرو فعلی" },
      { value: "current-crm", label: "CRM فعلی" },
      { value: "other", label: "سایر" },
    ],
    systemOptions: [
      { value: "online-booking", label: "رزرو آنلاین" },
      { value: "online-payment", label: "پرداخت آنلاین" },
      { value: "admin-dashboard", label: "داشبورد مدیریت" },
      { value: "customer-panel", label: "پنل مشتری" },
      { value: "crm", label: "CRM / مدیریت مشتری" },
      { value: "online-ordering", label: "سفارش آنلاین" },
      { value: "file-upload", label: "آپلود فایل" },
      { value: "auto-messages", label: "پیامک و ایمیل اتوماتیک" },
      { value: "status-tracking", label: "وضعیت سفارش یا رزرو" },
      { value: "reporting", label: "گزارش‌گیری" },
      { value: "roles", label: "نقش‌های کاربری مختلف" },
      { value: "ai", label: "هوش مصنوعی / AI" },
      { value: "automation", label: "اتوماسیون" },
      { value: "other", label: "سایر" },
    ],
    customerOptions: [
      { value: "signup-login", label: "ثبت‌نام / ورود" },
      { value: "book-appointment", label: "رزرو وقت" },
      { value: "pay", label: "پرداخت" },
      { value: "view-status", label: "مشاهده وضعیت رزرو یا سفارش" },
      { value: "history", label: "مشاهده جلسات یا سفارش‌های قبلی" },
      { value: "upload-file", label: "آپلود فایل" },
      { value: "receive-message", label: "دریافت پیامک یا ایمیل" },
      { value: "download-file", label: "دانلود خروجی یا فایل" },
      { value: "send-request", label: "ارسال درخواست یا توضیح" },
      { value: "not-sure", label: "فعلاً مطمئن نیستم" },
    ],
    adminOptions: [
      { value: "view-bookings", label: "دیدن رزروها" },
      { value: "manage-schedule", label: "مدیریت زمان‌بندی" },
      { value: "manage-orders", label: "مدیریت سفارش‌ها" },
      { value: "manage-customers", label: "مدیریت مشتری‌ها" },
      { value: "manage-payments", label: "مدیریت پرداخت‌ها" },
      { value: "change-status", label: "تغییر وضعیت‌ها" },
      { value: "files", label: "آپلود یا مشاهده فایل‌ها" },
      { value: "internal-notes", label: "یادداشت داخلی" },
      { value: "revenue-report", label: "گزارش درآمد" },
      { value: "manage-services", label: "مدیریت خدمات" },
      { value: "team-roles", label: "مدیریت کارمندان یا نقش‌ها" },
      { value: "access-levels", label: "سطح دسترسی متفاوت برای اعضای تیم" },
      { value: "not-sure", label: "فعلاً مطمئن نیستم" },
    ],
    sensitiveOptions: [
      { value: "normal", label: "نه، اطلاعات معمولی مشتری است" },
      { value: "private-files", label: "بله، فایل یا عکس مشتری ذخیره می‌شود" },
      { value: "medical", label: "بله، اطلاعات پزشکی یا حساس وجود دارد" },
      { value: "not-sure", label: "مطمئن نیستم" },
    ],
    budgetOptions: [
      { value: "under-750", label: "زیر £750" },
      { value: "750-1500", label: "£750 تا £1,500" },
      { value: "1500-3000", label: "£1,500 تا £3,000" },
      { value: "3000-plus", label: "£3,000+" },
      { value: "not-sure", label: "هنوز مطمئن نیستم" },
    ],
    timelineOptions: [
      { value: "asap", label: "هرچه زودتر" },
      { value: "2-4-weeks", label: "۲ تا ۴ هفته" },
      { value: "1-2-months", label: "۱ تا ۲ ماه" },
      { value: "2-plus-months", label: "بیشتر از ۲ ماه" },
      { value: "not-sure", label: "هنوز مطمئن نیستم" },
    ],
    sensitiveHelper: "اگر اطلاعات حساس یا پزشکی وجود داشته باشد، در proposal بخش امنیت، سطح دسترسی و مالکیت داده‌ها جداگانه بررسی می‌شود.",
  },
};

const aliasMap: Record<string, string> = {
  ar: "ar",
  de: "de",
  es: "es",
  fr: "fr",
  hi: "hi",
  it: "it",
  ja: "ja",
  ko: "ko",
  pt: "pt",
  ru: "ru",
  tr: "tr",
  zh: "zh",
};

const makeLocalizedCopy = (language: string, overrides: Partial<SystemReviewCopy>): SystemReviewCopy => ({
  ...systemReviewCopy.en,
  ...overrides,
  fields: { ...systemReviewCopy.en.fields, ...(overrides.fields || {}) },
  placeholders: { ...systemReviewCopy.en.placeholders, ...(overrides.placeholders || {}) },
});

systemReviewCopy.ar = makeLocalizedCopy("ar", {
  direction: "rtl",
  pageBadge: "طلب مراجعة النظام",
  pageTitle: "ابدأ مراجعة النظام",
  pageSubtitle: "أجب عن بعض الأسئلة الموجهة حتى نفهم عملك وسير العمل والنظام المناسب لك.",
  brandSignature: "From Idea to System",
  progressText: "الخطوة {{step}} من {{total}}",
  next: "التالي",
  previous: "السابق",
  submit: "إرسال طلب مراجعة النظام",
  sending: "جارٍ إرسال الطلب...",
  optional: "اختياري",
  privacyNote: "تُستخدم إجاباتك فقط لمراجعة المشروع واقتراح الخطوة المناسبة.",
  validationRequired: "يرجى إكمال الحقول المطلوبة قبل المتابعة.",
  validationEmail: "يرجى إدخال بريد عمل صحيح.",
  validationOther: "يرجى إضافة وصف قصير لخيار «أخرى».",
  validationConsent: "يرجى تأكيد المربع الأخير قبل الإرسال.",
  submitError: "تعذر إرسال الطلب الآن. يرجى المحاولة بعد قليل.",
  successTitle: "تم إرسال طلبك.",
  successBody: "سنراجع إجاباتك، وإذا كان المشروع مناسباً، سنتواصل معك لتنسيق جلسة مراجعة النظام.",
  backHome: "العودة إلى الرئيسية",
  consent: "أفهم أن هذا النموذج مخصص للمراجعة الأولية للمشروع، وإذا كان مناسباً سيتم التواصل معي لتنسيق جلسة مراجعة النظام.",
  fields: {
    name: "اسمك",
    businessName: "اسم النشاط التجاري",
    email: "بريد العمل",
    website: "الموقع الحالي أو رابط إنستغرام",
    other: "يرجى التوضيح",
    workflowNotes: "اشرح سير العمل الحالي باختصار",
    mainProblem: "المشكلة الرئيسية",
    sensitiveNotes: "ما نوع المعلومات أو الملفات المخزنة؟",
    finalNotes: "هل هناك شيء آخر يجب أن نعرفه؟",
    budget: "الميزانية التقريبية",
    timeline: "المدة المتوقعة",
  },
  placeholders: {
    name: "مثال: سارة أحمد",
    businessName: "مثال: عيادة أورا",
    email: "name@company.com",
    website: "https://... أو @yourpage",
    businessOther: "اشرح نوع نشاطك باختصار",
    workflowNotes: "شرح قصير يكفي.",
    mainProblem: "مثلاً: الحجوزات متفرقة، المدفوعات منفصلة، العملاء يطلبون تحديثات كثيرة، أو الفريق لا يستطيع إدارة كل شيء من لوحة واحدة.",
    systemOther: "ما الميزة الأخرى المطلوبة؟",
    sensitiveNotes: "مثلاً: صور العملاء، ملاحظات طبية، ملفات خاصة أو فواتير.",
    finalNotes: "أضف أي تفاصيل عن الفكرة أو الأدوات الحالية أو نظام مشابه تريد بناءه.",
  },
  steps: [
    { title: "لنبدأ بالتعرف على عملك", helper: "نحتاج بعض المعلومات الأساسية لمراجعة المشروع بشكل صحيح." },
    { title: "في أي مجال يعمل نشاطك؟", helper: "اختر الخيار الأقرب لعملك." },
    { title: "كيف يتم العمل حالياً؟", helper: "كيف يتواصل العملاء أو يحجزون أو يطلبون اليوم؟", question: "اختر كل قناة أو أداة مستخدمة حالياً." },
    { title: "ما أكبر مشكلة حالياً؟", helper: "إذا كان هناك جزء واحد يجب تحسينه أولاً، فما هو؟", question: "اكتب المشكلة الرئيسية بكلماتك." },
    { title: "ما الذي يجب أن يتضمنه النظام؟", helper: "اختر الأجزاء المهمة لنظامك." },
    { title: "ما الذي يجب أن يتمكن العميل من فعله؟", helper: "فكر في تجربة العميل داخل النظام." },
    { title: "ما الذي يحتاجه فريقك في لوحة الإدارة؟", helper: "اختر ما تحتاج إلى إدارته يومياً." },
    { title: "هل سيحفظ النظام بيانات حساسة أو ملفات خاصة؟", helper: "يساعدنا ذلك على مراجعة الوصول والأمان وملكية البيانات." },
    { title: "الميزانية والمدة التقريبية", helper: "نطاق تقريبي يكفي للمراجعة الأولى." },
    { title: "هل هناك شيء آخر يجب أن نعرفه؟", helper: "أضف أي سياق إضافي قبل الإرسال." },
  ],
  businessTypes: [
    { value: "beauty-health-clinic", label: "عيادة تجميل / صحة" },
    { value: "dental-medical", label: "أسنان / عيادة طبية" },
    { value: "print-advertising", label: "طباعة وإعلانات" },
    { value: "salon-nails-hair", label: "صالون / أظافر / شعر" },
    { value: "coach-consultant", label: "مدرب / مستشار / خدمة شخصية" },
    { value: "shop-boutique", label: "متجر / بوتيك" },
    { value: "restaurant-cafe", label: "مطعم / مقهى" },
    { value: "online-business", label: "نشاط إلكتروني" },
    { value: "saas-idea", label: "فكرة أو منتج SaaS" },
    { value: "other", label: "أخرى" },
  ],
  workflowOptions: [
    ...commonSocial,
    { value: "phone", label: "مكالمات هاتفية" },
    { value: "website-form", label: "نموذج الموقع" },
    { value: "sheets", label: "Google Sheets / Excel" },
    { value: "in-person", label: "حضوري" },
    { value: "current-booking", label: "نظام حجز حالي" },
    { value: "current-crm", label: "CRM حالي" },
    { value: "other", label: "أخرى" },
  ],
  sensitiveOptions: [
    { value: "normal", label: "لا، معلومات عملاء عادية فقط" },
    { value: "private-files", label: "نعم، تُخزن ملفات أو صور العملاء" },
    { value: "medical", label: "نعم، توجد معلومات طبية أو حساسة" },
    { value: "not-sure", label: "لست متأكداً" },
  ],
  sensitiveHelper: "إذا كانت هناك بيانات حساسة أو طبية، فسيتم مراجعة الأمان ومستويات الوصول وملكية البيانات بشكل منفصل في المقترح.",
});

systemReviewCopy.fr = makeLocalizedCopy("fr", {
  pageBadge: "Demande de revue système",
  pageTitle: "Démarrer une revue système",
  pageSubtitle: "Répondez à quelques questions guidées pour nous aider à comprendre votre activité, votre fonctionnement actuel et le système à créer.",
  brandSignature: "From Idea to System",
  progressText: "Étape {{step}} sur {{total}}",
  next: "Suivant",
  previous: "Retour",
  submit: "Envoyer la demande",
  sending: "Envoi en cours...",
  optional: "Facultatif",
  privacyNote: "Vos réponses servent uniquement à étudier le projet et à recommander la prochaine étape.",
  validationRequired: "Veuillez compléter les champs requis avant de continuer.",
  validationEmail: "Veuillez saisir un email professionnel valide.",
  validationOther: "Ajoutez une courte précision pour « Autre ».",
  validationConsent: "Veuillez confirmer la case finale avant l’envoi.",
  submitError: "La demande n’a pas pu être envoyée pour le moment. Réessayez dans quelques instants.",
  successTitle: "Votre demande a été envoyée.",
  successBody: "Nous allons étudier vos réponses et, si le projet correspond à notre accompagnement, nous vous contacterons pour organiser une session System Review.",
  backHome: "Retour à l’accueil",
  consent: "Je comprends que ce formulaire sert à une première revue du projet et que je serai contacté si le projet est adapté à une session System Review.",
  fields: {
    name: "Votre nom",
    businessName: "Nom de l’entreprise",
    email: "Email professionnel",
    website: "Site actuel ou lien Instagram",
    other: "Précisez",
    workflowNotes: "Décrivez brièvement le fonctionnement actuel",
    mainProblem: "Problème principal",
    sensitiveNotes: "Quels types d’informations ou de fichiers sont stockés ?",
    finalNotes: "Autre chose à savoir ?",
    budget: "Budget approximatif",
    timeline: "Délai souhaité",
  },
  placeholders: {
    name: "ex. Sara Martin",
    businessName: "ex. Aura Clinic",
    email: "nom@entreprise.com",
    website: "https://... ou @votrepage",
    businessOther: "Indiquez brièvement le type d’activité",
    workflowNotes: "Quelques lignes suffisent.",
    mainProblem: "Par exemple : réservations dispersées, paiements séparés, trop de demandes de suivi, données éparpillées ou équipe sans vrai panneau de gestion.",
    systemOther: "Que doit inclure le système en plus ?",
    sensitiveNotes: "Photos clients, notes médicales, fichiers privés, factures ou documents d’identité.",
    finalNotes: "Ajoutez tout détail utile sur l’idée, les outils actuels, les fichiers ou un système similaire.",
  },
  steps: [
    { title: "Commençons par votre activité", helper: "Quelques informations de base nous aident à étudier le projet correctement." },
    { title: "Dans quel domaine travaillez-vous ?", helper: "Choisissez l’option la plus proche de votre activité." },
    { title: "Comment travaillez-vous aujourd’hui ?", helper: "Comment les clients vous contactent, réservent ou commandent actuellement ?", question: "Sélectionnez les canaux ou outils utilisés aujourd’hui." },
    { title: "Quel est le problème principal ?", helper: "Si une seule partie devait être améliorée en premier, laquelle serait-ce ?", question: "Décrivez le problème avec vos mots." },
    { title: "Que doit contenir le système ?", helper: "Sélectionnez les éléments importants pour votre futur système." },
    { title: "Que doit pouvoir faire le client ?", helper: "Pensez à l’expérience client dans le système." },
    { title: "De quoi votre équipe a-t-elle besoin côté gestion ?", helper: "Choisissez ce que vous devez gérer au quotidien." },
    { title: "Le système stockera-t-il des données sensibles ou des fichiers privés ?", helper: "Cela nous aide à prévoir accès, sécurité et propriété des données." },
    { title: "Budget et calendrier approximatifs", helper: "Une fourchette suffit pour la première revue." },
    { title: "Autre chose à savoir ?", helper: "Ajoutez le contexte utile avant l’envoi." },
  ],
});

systemReviewCopy.es = makeLocalizedCopy("es", {
  pageBadge: "Solicitud de revisión del sistema",
  pageTitle: "Iniciar una revisión del sistema",
  pageSubtitle: "Responda unas preguntas guiadas para entender su negocio, su flujo actual y el sistema que necesita.",
  brandSignature: "From Idea to System",
  progressText: "Paso {{step}} de {{total}}",
  next: "Siguiente",
  previous: "Atrás",
  submit: "Enviar solicitud",
  sending: "Enviando solicitud...",
  optional: "Opcional",
  privacyNote: "Usamos sus respuestas solo para revisar el proyecto y recomendar el siguiente paso.",
  validationRequired: "Complete los campos obligatorios antes de continuar.",
  validationEmail: "Introduzca un email profesional válido.",
  validationOther: "Añada una breve explicación para «Otro».",
  validationConsent: "Confirme la casilla final antes de enviar.",
  submitError: "No se pudo enviar la solicitud ahora. Inténtelo de nuevo en unos momentos.",
  successTitle: "Su solicitud ha sido enviada.",
  successBody: "Revisaremos sus respuestas y, si el proyecto encaja, nos pondremos en contacto para coordinar una sesión de System Review.",
  backHome: "Volver al inicio",
  consent: "Entiendo que este formulario es para una revisión inicial del proyecto y que, si encaja, me contactarán para coordinar una sesión de System Review.",
});

systemReviewCopy.pt = makeLocalizedCopy("pt", {
  pageBadge: "Pedido de revisão do sistema",
  pageTitle: "Iniciar revisão do sistema",
  pageSubtitle: "Responda a algumas perguntas guiadas para entendermos o negócio, o fluxo atual e o sistema necessário.",
  progressText: "Passo {{step}} de {{total}}",
  next: "Seguinte",
  previous: "Anterior",
  submit: "Enviar pedido",
  sending: "A enviar pedido...",
  optional: "Opcional",
  privacyNote: "As respostas são usadas apenas para rever o projeto e recomendar o próximo passo.",
  validationRequired: "Preencha os campos obrigatórios antes de continuar.",
  validationEmail: "Introduza um email profissional válido.",
  validationOther: "Adicione uma nota curta para “Outro”.",
  validationConsent: "Confirme a caixa final antes de enviar.",
  submitError: "Não foi possível enviar o pedido agora. Tente novamente em instantes.",
  successTitle: "O seu pedido foi enviado.",
  successBody: "Vamos analisar as respostas e, se o projeto for adequado, entraremos em contacto para marcar uma sessão de System Review.",
  backHome: "Voltar ao início",
});

systemReviewCopy.de = makeLocalizedCopy("de", {
  pageBadge: "Anfrage zur Systemprüfung",
  pageTitle: "System Review starten",
  pageSubtitle: "Beantworten Sie einige geführte Fragen, damit wir Ihr Unternehmen, den aktuellen Ablauf und das benötigte System verstehen.",
  progressText: "Schritt {{step}} von {{total}}",
  next: "Weiter",
  previous: "Zurück",
  submit: "Anfrage senden",
  sending: "Anfrage wird gesendet...",
  optional: "Optional",
  privacyNote: "Ihre Antworten werden nur zur Projektprüfung und Empfehlung des nächsten Schritts genutzt.",
  validationRequired: "Bitte füllen Sie die Pflichtfelder aus, bevor Sie fortfahren.",
  validationEmail: "Bitte geben Sie eine gültige geschäftliche E-Mail ein.",
  validationOther: "Bitte ergänzen Sie eine kurze Notiz zu „Sonstiges“.",
  validationConsent: "Bitte bestätigen Sie die letzte Checkbox vor dem Senden.",
  submitError: "Die Anfrage konnte gerade nicht gesendet werden. Bitte versuchen Sie es gleich erneut.",
  successTitle: "Ihre Anfrage wurde gesendet.",
  successBody: "Wir prüfen Ihre Antworten und melden uns, falls das Projekt für eine System-Review-Session geeignet ist.",
  backHome: "Zur Startseite",
});

systemReviewCopy.it = makeLocalizedCopy("it", {
  pageBadge: "Richiesta di revisione sistema",
  pageTitle: "Avvia una revisione del sistema",
  pageSubtitle: "Rispondi a poche domande guidate per aiutarci a capire attività, flusso attuale e sistema necessario.",
  progressText: "Passo {{step}} di {{total}}",
  next: "Avanti",
  previous: "Indietro",
  submit: "Invia richiesta",
  sending: "Invio in corso...",
  optional: "Opzionale",
  privacyNote: "Le risposte sono usate solo per valutare il progetto e suggerire il prossimo passo.",
  validationRequired: "Completa i campi obbligatori prima di continuare.",
  validationEmail: "Inserisci un’email aziendale valida.",
  validationOther: "Aggiungi una breve nota per “Altro”.",
  validationConsent: "Conferma la casella finale prima di inviare.",
  submitError: "Non è stato possibile inviare la richiesta. Riprova tra poco.",
  successTitle: "La richiesta è stata inviata.",
  successBody: "Analizzeremo le risposte e, se il progetto è adatto, ti contatteremo per organizzare una sessione System Review.",
  backHome: "Torna alla home",
});

systemReviewCopy.tr = makeLocalizedCopy("tr", {
  pageBadge: "Sistem inceleme talebi",
  pageTitle: "Sistem incelemesi başlatın",
  pageSubtitle: "İşinizi, mevcut akışı ve ihtiyaç duyduğunuz sistemi anlayabilmemiz için birkaç yönlendirmeli soruyu yanıtlayın.",
  progressText: "Adım {{step}} / {{total}}",
  next: "İleri",
  previous: "Geri",
  submit: "Talebi gönder",
  sending: "Talep gönderiliyor...",
  optional: "İsteğe bağlı",
  privacyNote: "Yanıtlarınız yalnızca projeyi incelemek ve doğru sonraki adımı önermek için kullanılır.",
  validationRequired: "Devam etmeden önce zorunlu alanları tamamlayın.",
  validationEmail: "Lütfen geçerli bir iş e-postası girin.",
  validationOther: "“Diğer” için kısa bir açıklama ekleyin.",
  validationConsent: "Göndermeden önce son onayı işaretleyin.",
  submitError: "Talep şu anda gönderilemedi. Lütfen biraz sonra tekrar deneyin.",
  successTitle: "Talebiniz gönderildi.",
  successBody: "Yanıtlarınızı inceleyeceğiz ve proje uygunsa bir System Review oturumu için sizinle iletişime geçeceğiz.",
  backHome: "Ana sayfaya dön",
});

systemReviewCopy.ru = makeLocalizedCopy("ru", {
  pageBadge: "Запрос на системный разбор",
  pageTitle: "Начать System Review",
  pageSubtitle: "Ответьте на несколько вопросов, чтобы мы поняли бизнес, текущий процесс и систему, которая вам нужна.",
  progressText: "Шаг {{step}} из {{total}}",
  next: "Далее",
  previous: "Назад",
  submit: "Отправить запрос",
  sending: "Отправляем запрос...",
  optional: "Необязательно",
  privacyNote: "Ответы используются только для оценки проекта и рекомендации следующего шага.",
  validationRequired: "Заполните обязательные поля, чтобы продолжить.",
  validationEmail: "Введите корректный рабочий email.",
  validationOther: "Добавьте короткое пояснение для «Другое».",
  validationConsent: "Подтвердите финальный пункт перед отправкой.",
  submitError: "Сейчас не удалось отправить запрос. Попробуйте ещё раз чуть позже.",
  successTitle: "Ваш запрос отправлен.",
  successBody: "Мы изучим ответы и, если проект подходит, свяжемся с вами для согласования сессии System Review.",
  backHome: "На главную",
});

systemReviewCopy.zh = makeLocalizedCopy("zh", {
  pageBadge: "系统评估申请",
  pageTitle: "开始系统评估",
  pageSubtitle: "请回答几个引导问题，帮助我们了解您的业务、当前流程以及需要构建的系统。",
  progressText: "第 {{step}} 步，共 {{total}} 步",
  next: "下一步",
  previous: "上一步",
  submit: "提交系统评估申请",
  sending: "正在提交...",
  optional: "可选",
  privacyNote: "您的回答仅用于项目初步评估和下一步建议。",
  validationRequired: "请先完成本步骤的必填内容。",
  validationEmail: "请输入有效的工作邮箱。",
  validationOther: "请为“其他”补充一句说明。",
  validationConsent: "提交前请确认最后的勾选项。",
  submitError: "当前无法提交申请，请稍后再试。",
  successTitle: "您的申请已提交。",
  successBody: "我们会查看您的回答。如果项目适合，我们会联系您安排 System Review 会议。",
  backHome: "返回首页",
});

systemReviewCopy.ko = makeLocalizedCopy("ko", {
  pageBadge: "시스템 리뷰 요청",
  pageTitle: "시스템 리뷰 시작",
  pageSubtitle: "비즈니스, 현재 흐름, 필요한 시스템을 이해할 수 있도록 몇 가지 질문에 답해주세요.",
  progressText: "{{total}}단계 중 {{step}}단계",
  next: "다음",
  previous: "이전",
  submit: "시스템 리뷰 요청 보내기",
  sending: "요청을 보내는 중...",
  optional: "선택 사항",
  privacyNote: "답변은 프로젝트 검토와 다음 단계 제안에만 사용됩니다.",
  validationRequired: "계속하려면 필수 항목을 입력해주세요.",
  validationEmail: "유효한 업무용 이메일을 입력해주세요.",
  validationOther: "“기타”에 대한 짧은 설명을 추가해주세요.",
  validationConsent: "제출 전 마지막 확인란을 체크해주세요.",
  submitError: "지금은 요청을 보낼 수 없습니다. 잠시 후 다시 시도해주세요.",
  successTitle: "요청이 전송되었습니다.",
  successBody: "답변을 검토한 뒤 프로젝트가 적합하면 System Review 세션 조율을 위해 연락드리겠습니다.",
  backHome: "홈으로 돌아가기",
});

systemReviewCopy.ja = makeLocalizedCopy("ja", {
  pageBadge: "システムレビュー依頼",
  pageTitle: "システムレビューを始める",
  pageSubtitle: "事業内容、現在の流れ、必要なシステムを理解するために、いくつかの質問にお答えください。",
  progressText: "{{total}}ステップ中 {{step}}",
  next: "次へ",
  previous: "戻る",
  submit: "システムレビューを送信",
  sending: "送信中...",
  optional: "任意",
  privacyNote: "回答内容は、プロジェクトの初期確認と次のステップの提案にのみ使用します。",
  validationRequired: "続行するには必須項目を入力してください。",
  validationEmail: "有効なビジネス用メールアドレスを入力してください。",
  validationOther: "「その他」について短く補足してください。",
  validationConsent: "送信前に最後の確認項目にチェックしてください。",
  submitError: "現在送信できません。少し時間を置いて再度お試しください。",
  successTitle: "リクエストを送信しました。",
  successBody: "内容を確認し、プロジェクトが適している場合は System Review の日程調整についてご連絡します。",
  backHome: "ホームへ戻る",
});

systemReviewCopy.hi = makeLocalizedCopy("hi", {
  pageBadge: "सिस्टम रिव्यू अनुरोध",
  pageTitle: "सिस्टम रिव्यू शुरू करें",
  pageSubtitle: "अपने व्यवसाय, मौजूदा काम के तरीके और ज़रूरी सिस्टम को समझने के लिए कुछ सरल सवालों के जवाब दें।",
  progressText: "चरण {{step}} / {{total}}",
  next: "आगे",
  previous: "पीछे",
  submit: "सिस्टम रिव्यू अनुरोध भेजें",
  sending: "अनुरोध भेजा जा रहा है...",
  optional: "वैकल्पिक",
  privacyNote: "आपके जवाब केवल प्रोजेक्ट की समीक्षा और सही अगले कदम के सुझाव के लिए उपयोग होंगे।",
  validationRequired: "आगे बढ़ने से पहले आवश्यक जानकारी पूरी करें।",
  validationEmail: "कृपया मान्य कार्य ईमेल दर्ज करें।",
  validationOther: "“अन्य” के लिए एक छोटा विवरण जोड़ें।",
  validationConsent: "भेजने से पहले अंतिम checkbox की पुष्टि करें।",
  submitError: "अभी अनुरोध नहीं भेजा जा सका। कृपया थोड़ी देर बाद फिर कोशिश करें।",
  successTitle: "आपका अनुरोध भेज दिया गया है।",
  successBody: "हम आपके जवाबों की समीक्षा करेंगे और यदि प्रोजेक्ट उपयुक्त हुआ तो System Review सत्र के लिए आपसे संपर्क करेंगे।",
  backHome: "होम पर लौटें",
});

type ChoiceGroup =
  | "businessTypes"
  | "workflowOptions"
  | "systemOptions"
  | "customerOptions"
  | "adminOptions"
  | "sensitiveOptions"
  | "budgetOptions"
  | "timelineOptions";

const valuesByGroup: Record<ChoiceGroup, string[]> = {
  businessTypes: systemReviewCopy.en.businessTypes.map((choice) => choice.value),
  workflowOptions: systemReviewCopy.en.workflowOptions.map((choice) => choice.value),
  systemOptions: systemReviewCopy.en.systemOptions.map((choice) => choice.value),
  customerOptions: systemReviewCopy.en.customerOptions.map((choice) => choice.value),
  adminOptions: systemReviewCopy.en.adminOptions.map((choice) => choice.value),
  sensitiveOptions: systemReviewCopy.en.sensitiveOptions.map((choice) => choice.value),
  budgetOptions: systemReviewCopy.en.budgetOptions.map((choice) => choice.value),
  timelineOptions: systemReviewCopy.en.timelineOptions.map((choice) => choice.value),
};

const applyReviewLocale = (
  language: string,
  config: Partial<SystemReviewCopy> & { choiceLabels?: Partial<Record<ChoiceGroup, string>> },
) => {
  const target = systemReviewCopy[language] || makeLocalizedCopy(language, {});
  systemReviewCopy[language] = target;

  Object.assign(target, config);
  if (config.fields) target.fields = { ...target.fields, ...config.fields };
  if (config.placeholders) target.placeholders = { ...target.placeholders, ...config.placeholders };

  Object.entries(config.choiceLabels || {}).forEach(([group, labels]) => {
    const values = valuesByGroup[group as ChoiceGroup];
    const splitLabels = String(labels).split("|");
    (target as unknown as Record<string, ReviewChoice[]>)[group] = values.map((value, index) => ({
      value,
      label: splitLabels[index] || value,
    }));
  });
};

applyReviewLocale("fr", {
  fields: {
    name: "Votre nom",
    businessName: "Nom de l’entreprise",
    email: "Email professionnel",
    website: "Site actuel ou lien Instagram",
    other: "Précisez",
    workflowNotes: "Décrivez brièvement le fonctionnement actuel",
    mainProblem: "Problème principal",
    sensitiveNotes: "Quels types d’informations ou de fichiers sont stockés ?",
    finalNotes: "Autre chose à savoir ?",
    budget: "Budget approximatif",
    timeline: "Délai souhaité",
  },
  placeholders: {
    name: "ex. Sara Martin",
    businessName: "ex. Aura Clinic",
    email: "nom@entreprise.com",
    website: "https://... ou @votrepage",
    businessOther: "Indiquez brièvement le type d’activité",
    workflowNotes: "Quelques lignes suffisent.",
    mainProblem: "Par exemple : réservations dispersées, paiements séparés, trop de demandes de suivi ou données éparpillées.",
    systemOther: "Que doit inclure le système en plus ?",
    sensitiveNotes: "Photos clients, notes médicales, fichiers privés, factures ou documents d’identité.",
    finalNotes: "Ajoutez tout détail utile sur l’idée, les outils actuels, les fichiers ou un système similaire.",
  },
  choiceLabels: {
    businessTypes: "Clinique beauté / santé|Cabinet dentaire / médical|Impression et publicité|Salon / ongles / coiffure|Coach / consultant / service personnel|Boutique / magasin|Restaurant / café|Business en ligne|Idée ou produit SaaS|Autre",
    workflowOptions: "Instagram DM|WhatsApp|Appels téléphoniques|Formulaire du site|Google Sheets / Excel|En personne|Système de réservation actuel|CRM actuel|Autre",
    systemOptions: "Réservation en ligne|Paiement en ligne|Tableau de bord admin|Espace client|CRM / gestion client|Commande en ligne|Téléversement de fichiers|SMS et emails automatiques|Statut de commande ou réservation|Rapports|Rôles utilisateurs différents|IA|Automatisation|Autre",
    customerOptions: "Créer un compte / se connecter|Réserver un rendez-vous|Payer|Voir le statut|Voir l’historique|Téléverser un fichier|Recevoir SMS ou email|Télécharger un fichier|Envoyer une demande|Pas encore sûr",
    adminOptions: "Voir les réservations|Gérer le planning|Gérer les commandes|Gérer les clients|Gérer les paiements|Changer les statuts|Ajouter ou voir des fichiers|Notes internes|Rapport de revenus|Gérer les services|Gérer l’équipe ou les rôles|Niveaux d’accès différents|Pas encore sûr",
    sensitiveOptions: "Non, seulement des informations client classiques|Oui, fichiers ou photos client|Oui, données médicales ou sensibles|Je ne suis pas sûr",
    budgetOptions: "Moins de £750|£750 à £1,500|£1,500 à £3,000|£3,000+|Pas encore sûr",
    timelineOptions: "Dès que possible|2 à 4 semaines|1 à 2 mois|Plus de 2 mois|Pas encore sûr",
  },
  sensitiveHelper: "Si des données sensibles ou médicales sont concernées, la proposition inclura une revue séparée de la sécurité, des accès et de la propriété des données.",
});

applyReviewLocale("es", {
  fields: {
    name: "Su nombre",
    businessName: "Nombre del negocio",
    email: "Email profesional",
    website: "Sitio web actual o enlace de Instagram",
    other: "Explíquelo brevemente",
    workflowNotes: "Describa brevemente el flujo actual",
    mainProblem: "Problema principal",
    sensitiveNotes: "¿Qué tipo de información o archivos se guardan?",
    finalNotes: "¿Algo más que debamos saber?",
    budget: "Presupuesto aproximado",
    timeline: "Plazo ideal",
  },
  placeholders: {
    name: "Ej. Sara García",
    businessName: "Ej. Clínica Aura",
    email: "nombre@empresa.com",
    website: "https://... o @supagina",
    businessOther: "Explique qué tipo de negocio es",
    workflowNotes: "Con unas líneas es suficiente.",
    mainProblem: "Por ejemplo: reservas dispersas, pagos separados, demasiadas consultas de seguimiento, datos en varios lugares o falta de panel de gestión.",
    systemOther: "¿Qué más debería incluir el sistema?",
    sensitiveNotes: "Fotos de clientes, notas médicas, archivos privados, facturas o documentos.",
    finalNotes: "Comparta cualquier detalle sobre la idea, herramientas actuales, archivos o sistemas similares.",
  },
  steps: [
    { title: "Primero, conozcamos su negocio", helper: "Necesitamos algunos datos básicos para revisar bien el proyecto." },
    { title: "¿En qué sector trabaja su negocio?", helper: "Elija la opción más cercana." },
    { title: "¿Cómo funciona ahora el trabajo?", helper: "¿Cómo contactan, reservan o hacen pedidos sus clientes?", question: "Seleccione todos los canales o herramientas actuales." },
    { title: "¿Cuál es el mayor problema actual?", helper: "Si una parte tuviera que mejorar primero, ¿cuál sería?", question: "Describa el problema con sus propias palabras." },
    { title: "¿Qué debe incluir el sistema?", helper: "Elija las partes importantes para su sistema." },
    { title: "¿Qué debe poder hacer el cliente?", helper: "Piense en la experiencia del cliente dentro del sistema." },
    { title: "¿Qué necesita su equipo en el panel de gestión?", helper: "Seleccione lo que necesita gestionar día a día." },
    { title: "¿El sistema guardará datos sensibles o archivos privados?", helper: "Esto ayuda a revisar acceso, seguridad y propiedad de datos." },
    { title: "Presupuesto y plazo aproximados", helper: "Un rango aproximado es suficiente para la primera revisión." },
    { title: "¿Algo más que debamos saber?", helper: "Añada cualquier contexto antes de enviar." },
  ],
  choiceLabels: {
    businessTypes: "Clínica de belleza / salud|Dental / clínica médica|Impresión y publicidad|Salón / uñas / cabello|Coach / consultor / servicio personal|Tienda / boutique|Restaurante / café|Negocio online|Idea o producto SaaS|Otro",
    workflowOptions: "Instagram DM|WhatsApp|Llamadas telefónicas|Formulario web|Google Sheets / Excel|Presencial|Sistema de reservas actual|CRM actual|Otro",
    systemOptions: "Reservas online|Pago online|Panel de administración|Panel de cliente|CRM / gestión de clientes|Pedidos online|Subida de archivos|SMS y emails automáticos|Estado de pedido o reserva|Informes|Roles de usuario diferentes|IA|Automatización|Otro",
    customerOptions: "Registrarse / iniciar sesión|Reservar cita|Pagar|Ver estado|Ver historial|Subir archivo|Recibir SMS o email|Descargar archivo|Enviar solicitud o nota|Aún no estoy seguro",
    adminOptions: "Ver reservas|Gestionar calendario|Gestionar pedidos|Gestionar clientes|Gestionar pagos|Cambiar estados|Subir o ver archivos|Notas internas|Informe de ingresos|Gestionar servicios|Gestionar equipo o roles|Niveles de acceso diferentes|Aún no estoy seguro",
    sensitiveOptions: "No, solo información normal de clientes|Sí, archivos o fotos de clientes|Sí, información médica o sensible|No estoy seguro",
    budgetOptions: "Menos de £750|£750 a £1,500|£1,500 a £3,000|£3,000+|Aún no estoy seguro",
    timelineOptions: "Lo antes posible|2 a 4 semanas|1 a 2 meses|Más de 2 meses|Aún no estoy seguro",
  },
  sensitiveHelper: "Si hay datos sensibles o médicos, la propuesta revisará por separado seguridad, niveles de acceso y propiedad de datos.",
});

applyReviewLocale("de", {
  consent: "Ich verstehe, dass dieses Formular der ersten Projektprüfung dient und ich kontaktiert werde, falls das Projekt für eine System-Review-Session geeignet ist.",
  fields: {
    name: "Ihr Name",
    businessName: "Name des Unternehmens",
    email: "Geschäftliche E-Mail",
    website: "Aktuelle Website oder Instagram-Link",
    other: "Bitte kurz erklären",
    workflowNotes: "Aktuellen Ablauf kurz beschreiben",
    mainProblem: "Hauptproblem",
    sensitiveNotes: "Welche Informationen oder Dateien werden gespeichert?",
    finalNotes: "Gibt es noch etwas Wichtiges?",
    budget: "Ungefähres Budget",
    timeline: "Gewünschter Zeitrahmen",
  },
  placeholders: {
    name: "z. B. Sara Weber",
    businessName: "z. B. Aura Clinic",
    email: "name@unternehmen.com",
    website: "https://... oder @ihreseite",
    businessOther: "Beschreiben Sie kurz die Art des Unternehmens",
    workflowNotes: "Ein paar Zeilen reichen aus.",
    mainProblem: "Zum Beispiel: Buchungen sind verstreut, Zahlungen getrennt, Kunden fragen häufig nach Updates oder das Team hat kein zentrales Panel.",
    systemOther: "Was soll das System noch enthalten?",
    sensitiveNotes: "Kundenfotos, medizinische Notizen, private Dateien, Rechnungen oder Ausweise.",
    finalNotes: "Teilen Sie weitere Details zur Idee, zu aktuellen Tools, Dateien oder ähnlichen Systemen.",
  },
  steps: [
    { title: "Zuerst Ihr Unternehmen verstehen", helper: "Ein paar Basisdaten helfen uns, das Projekt richtig einzuordnen." },
    { title: "In welchem Bereich arbeitet Ihr Unternehmen?", helper: "Wählen Sie die passendste Option." },
    { title: "Wie läuft die Arbeit aktuell ab?", helper: "Wie kontaktieren, buchen oder bestellen Kunden heute?", question: "Wählen Sie alle aktuellen Kanäle oder Tools." },
    { title: "Was ist aktuell das größte Problem?", helper: "Wenn ein Bereich zuerst besser werden sollte, welcher wäre es?", question: "Beschreiben Sie das Problem in eigenen Worten." },
    { title: "Was soll das System enthalten?", helper: "Wählen Sie die wichtigen Bestandteile aus." },
    { title: "Was sollen Kunden im System tun können?", helper: "Denken Sie an die Kundenerfahrung im System." },
    { title: "Was braucht Ihr Team im Admin-Bereich?", helper: "Wählen Sie aus, was täglich verwaltet werden muss." },
    { title: "Speichert das System sensible Daten oder private Dateien?", helper: "Das hilft uns bei Zugriff, Sicherheit und Dateneigentum." },
    { title: "Budget und Zeitrahmen", helper: "Eine grobe Spanne reicht für die erste Prüfung." },
    { title: "Noch etwas, das wir wissen sollten?", helper: "Fügen Sie vor dem Senden zusätzlichen Kontext hinzu." },
  ],
  choiceLabels: {
    businessTypes: "Beauty- / Gesundheitsklinik|Zahnarzt / medizinische Klinik|Druck und Werbung|Salon / Nägel / Haare|Coach / Berater / persönliche Dienstleistung|Shop / Boutique|Restaurant / Café|Online-Business|SaaS-Idee oder Produkt|Sonstiges",
    workflowOptions: "Instagram DM|WhatsApp|Telefonanrufe|Website-Formular|Google Sheets / Excel|Vor Ort|Aktuelles Buchungssystem|Aktuelles CRM|Sonstiges",
    systemOptions: "Online-Buchung|Online-Zahlung|Admin-Dashboard|Kundenbereich|CRM / Kundenmanagement|Online-Bestellung|Dateiupload|Automatische SMS und E-Mails|Status von Bestellung oder Buchung|Reporting|Verschiedene Nutzerrollen|KI|Automatisierung|Sonstiges",
    customerOptions: "Registrieren / einloggen|Termin buchen|Bezahlen|Status ansehen|Vergangene Termine oder Bestellungen ansehen|Datei hochladen|SMS oder E-Mail erhalten|Datei herunterladen|Anfrage oder Notiz senden|Noch nicht sicher",
    adminOptions: "Buchungen ansehen|Zeitplan verwalten|Bestellungen verwalten|Kunden verwalten|Zahlungen verwalten|Status ändern|Dateien hochladen oder ansehen|Interne Notizen|Umsatzbericht|Services verwalten|Mitarbeiter oder Rollen verwalten|Unterschiedliche Zugriffsebenen|Noch nicht sicher",
    sensitiveOptions: "Nein, nur normale Kundendaten|Ja, Kundenfotos oder Dateien|Ja, medizinische oder sensible Daten|Nicht sicher",
    budgetOptions: "Unter £750|£750 bis £1,500|£1,500 bis £3,000|£3,000+|Noch nicht sicher",
    timelineOptions: "So bald wie möglich|2 bis 4 Wochen|1 bis 2 Monate|Mehr als 2 Monate|Noch nicht sicher",
  },
  sensitiveHelper: "Wenn sensible oder medizinische Daten betroffen sind, prüfen wir Sicherheit, Zugriffslevel und Dateneigentum separat im Angebot.",
});

applyReviewLocale("pt", {
  consent: "Compreendo que este formulário serve para uma revisão inicial do projeto e que, se o projeto for adequado, serei contactado para marcar uma sessão de System Review.",
  fields: {
    name: "O seu nome",
    businessName: "Nome do negócio",
    email: "Email profissional",
    website: "Site atual ou link do Instagram",
    other: "Explique brevemente",
    workflowNotes: "Descreva brevemente o fluxo atual",
    mainProblem: "Problema principal",
    sensitiveNotes: "Que tipo de informação ou ficheiros são guardados?",
    finalNotes: "Há mais alguma coisa que devamos saber?",
    budget: "Orçamento aproximado",
    timeline: "Prazo ideal",
  },
  placeholders: {
    name: "ex. Sara Silva",
    businessName: "ex. Clínica Aura",
    email: "nome@empresa.com",
    website: "https://... ou @asuapagina",
    businessOther: "Diga brevemente que tipo de negócio é",
    workflowNotes: "Algumas linhas são suficientes.",
    mainProblem: "Por exemplo: reservas dispersas, pagamentos separados, clientes pedem muitos updates ou a equipa não tem um painel central.",
    systemOther: "O que mais deve entrar no sistema?",
    sensitiveNotes: "Fotos de clientes, notas médicas, ficheiros privados, faturas ou documentos.",
    finalNotes: "Partilhe detalhes sobre a ideia, ferramentas atuais, ficheiros ou sistemas semelhantes.",
  },
  steps: [
    { title: "Vamos conhecer o seu negócio", helper: "Alguns dados básicos ajudam-nos a rever melhor o projeto." },
    { title: "Em que área atua o seu negócio?", helper: "Escolha a opção mais próxima." },
    { title: "Como funciona hoje?", helper: "Como os clientes contactam, reservam ou fazem pedidos?", question: "Selecione os canais ou ferramentas usados atualmente." },
    { title: "Qual é o maior problema agora?", helper: "Se uma parte tivesse de melhorar primeiro, qual seria?", question: "Descreva o problema com as suas palavras." },
    { title: "O que o sistema deve incluir?", helper: "Escolha as partes importantes para o sistema." },
    { title: "O que o cliente deve conseguir fazer?", helper: "Pense na experiência do cliente dentro do sistema." },
    { title: "O que a equipa precisa no painel de gestão?", helper: "Escolha o que precisa gerir no dia a dia." },
    { title: "O sistema vai guardar dados sensíveis ou ficheiros privados?", helper: "Isto ajuda-nos a rever acesso, segurança e propriedade dos dados." },
    { title: "Orçamento e prazo aproximados", helper: "Uma estimativa é suficiente para a primeira revisão." },
    { title: "Mais alguma coisa que devamos saber?", helper: "Acrescente contexto antes de enviar." },
  ],
  choiceLabels: {
    businessTypes: "Clínica de beleza / saúde|Dentária / clínica médica|Impressão e publicidade|Salão / unhas / cabelo|Coach / consultor / serviço pessoal|Loja / boutique|Restaurante / café|Negócio online|Ideia ou produto SaaS|Outro",
    workflowOptions: "Instagram DM|WhatsApp|Chamadas telefónicas|Formulário do site|Google Sheets / Excel|Presencial|Sistema de reservas atual|CRM atual|Outro",
    systemOptions: "Reservas online|Pagamento online|Painel de gestão|Painel do cliente|CRM / gestão de clientes|Pedidos online|Upload de ficheiros|SMS e emails automáticos|Estado de pedido ou reserva|Relatórios|Diferentes papéis de utilizador|IA|Automação|Outro",
    customerOptions: "Registar / entrar|Marcar horário|Pagar|Ver estado|Ver histórico|Enviar ficheiro|Receber SMS ou email|Descarregar ficheiro|Enviar pedido ou nota|Ainda não tenho a certeza",
    adminOptions: "Ver reservas|Gerir agenda|Gerir pedidos|Gerir clientes|Gerir pagamentos|Alterar estados|Enviar ou ver ficheiros|Notas internas|Relatório de receita|Gerir serviços|Gerir equipa ou papéis|Níveis de acesso diferentes|Ainda não tenho a certeza",
    sensitiveOptions: "Não, apenas informação normal de clientes|Sim, ficheiros ou fotos de clientes|Sim, dados médicos ou sensíveis|Não tenho a certeza",
    budgetOptions: "Abaixo de £750|£750 a £1,500|£1,500 a £3,000|£3,000+|Ainda não tenho a certeza",
    timelineOptions: "O mais cedo possível|2 a 4 semanas|1 a 2 meses|Mais de 2 meses|Ainda não tenho a certeza",
  },
  sensitiveHelper: "Se existirem dados sensíveis ou médicos, a proposta irá rever separadamente segurança, níveis de acesso e propriedade dos dados.",
});

applyReviewLocale("it", {
  consent: "Capisco che questo modulo serve per una prima valutazione del progetto e che, se il progetto è adatto, sarò contattato per organizzare una sessione System Review.",
  fields: {
    name: "Il tuo nome",
    businessName: "Nome dell’attività",
    email: "Email di lavoro",
    website: "Sito attuale o link Instagram",
    other: "Spiega brevemente",
    workflowNotes: "Descrivi brevemente il flusso attuale",
    mainProblem: "Problema principale",
    sensitiveNotes: "Che tipo di informazioni o file vengono salvati?",
    finalNotes: "C’è altro che dovremmo sapere?",
    budget: "Budget indicativo",
    timeline: "Tempistica ideale",
  },
  placeholders: {
    name: "es. Sara Rossi",
    businessName: "es. Aura Clinic",
    email: "nome@azienda.com",
    website: "https://... o @tuapagina",
    businessOther: "Descrivi brevemente il tipo di attività",
    workflowNotes: "Bastano poche righe.",
    mainProblem: "Ad esempio: prenotazioni sparse, pagamenti separati, troppe richieste di aggiornamento o assenza di un pannello unico.",
    systemOther: "Cos’altro dovrebbe includere il sistema?",
    sensitiveNotes: "Foto clienti, note mediche, file privati, fatture o documenti.",
    finalNotes: "Condividi dettagli su idea, strumenti attuali, file o sistemi simili.",
  },
  choiceLabels: {
    businessTypes: "Clinica beauty / salute|Dentale / clinica medica|Stampa e pubblicità|Salone / unghie / capelli|Coach / consulente / servizio personale|Negozio / boutique|Ristorante / caffè|Business online|Idea o prodotto SaaS|Altro",
    workflowOptions: "Instagram DM|WhatsApp|Telefonate|Modulo del sito|Google Sheets / Excel|Di persona|Sistema di prenotazione attuale|CRM attuale|Altro",
    systemOptions: "Prenotazione online|Pagamento online|Dashboard admin|Pannello cliente|CRM / gestione clienti|Ordini online|Caricamento file|SMS ed email automatiche|Stato ordine o prenotazione|Reportistica|Ruoli utente diversi|AI|Automazione|Altro",
    customerOptions: "Registrarsi / accedere|Prenotare|Pagare|Vedere lo stato|Vedere storico|Caricare file|Ricevere SMS o email|Scaricare file|Inviare richiesta o nota|Non sono ancora sicuro",
    adminOptions: "Vedere prenotazioni|Gestire calendario|Gestire ordini|Gestire clienti|Gestire pagamenti|Cambiare stati|Caricare o vedere file|Note interne|Report ricavi|Gestire servizi|Gestire team o ruoli|Livelli di accesso diversi|Non sono ancora sicuro",
    sensitiveOptions: "No, solo dati cliente normali|Sì, file o foto cliente|Sì, dati medici o sensibili|Non sono sicuro",
    budgetOptions: "Sotto £750|£750 - £1,500|£1,500 - £3,000|£3,000+|Non sono ancora sicuro",
    timelineOptions: "Il prima possibile|2-4 settimane|1-2 mesi|Più di 2 mesi|Non sono ancora sicuro",
  },
  steps: [
    { title: "Partiamo dalla tua attività", helper: "Alcune informazioni di base ci aiutano a valutare meglio il progetto." },
    { title: "In che settore lavori?", helper: "Scegli l’opzione più vicina alla tua attività." },
    { title: "Come funziona oggi il lavoro?", helper: "Come ti contattano, prenotano o ordinano i clienti?", question: "Seleziona i canali o strumenti usati oggi." },
    { title: "Qual è il problema più grande?", helper: "Se una parte dovesse migliorare per prima, quale sarebbe?", question: "Descrivi il problema con parole tue." },
    { title: "Cosa deve includere il sistema?", helper: "Scegli le parti importanti per il tuo sistema." },
    { title: "Cosa deve poter fare il cliente?", helper: "Pensa all’esperienza del cliente dentro il sistema." },
    { title: "Cosa serve al team nel pannello di gestione?", helper: "Scegli cosa va gestito ogni giorno." },
    { title: "Il sistema salverà dati sensibili o file privati?", helper: "Questo ci aiuta a valutare accessi, sicurezza e proprietà dei dati." },
    { title: "Budget e tempistiche indicative", helper: "Una fascia indicativa basta per la prima valutazione." },
    { title: "C’è altro che dovremmo sapere?", helper: "Aggiungi il contesto utile prima dell’invio." },
  ],
  sensitiveHelper: "Se sono presenti dati sensibili o medici, nella proposta valuteremo separatamente sicurezza, livelli di accesso e proprietà dei dati.",
});

applyReviewLocale("tr", {
  consent: "Bu formun proje için ilk değerlendirme amacıyla kullanıldığını ve proje uygunsa System Review oturumu için benimle iletişime geçileceğini anlıyorum.",
  fields: {
    name: "Adınız",
    businessName: "İşletme adı",
    email: "İş e-postası",
    website: "Mevcut web sitesi veya Instagram linki",
    other: "Kısaca açıklayın",
    workflowNotes: "Mevcut iş akışını kısaca anlatın",
    mainProblem: "Ana problem",
    sensitiveNotes: "Ne tür bilgi veya dosyalar saklanıyor?",
    finalNotes: "Bilmemiz gereken başka bir şey var mı?",
    budget: "Yaklaşık bütçe",
    timeline: "Hedef zaman",
  },
  placeholders: {
    name: "örn. Sara Yılmaz",
    businessName: "örn. Aura Clinic",
    email: "ad@sirket.com",
    website: "https://... veya @sayfaniz",
    businessOther: "İşletme türünü kısaca yazın",
    workflowNotes: "Birkaç satır yeterli.",
    mainProblem: "Örneğin: rezervasyonlar dağınık, ödemeler ayrı, müşteriler çok güncelleme soruyor veya ekip tek panelden yönetemiyor.",
    systemOther: "Sistemde başka ne olmalı?",
    sensitiveNotes: "Müşteri fotoğrafları, tıbbi notlar, özel dosyalar, faturalar veya belgeler.",
    finalNotes: "Fikir, mevcut araçlar, dosyalar veya benzer sistemler hakkında detay paylaşın.",
  },
  choiceLabels: {
    businessTypes: "Güzellik / sağlık kliniği|Diş / medikal klinik|Baskı ve reklam|Salon / tırnak / saç|Koç / danışman / kişisel hizmet|Mağaza / butik|Restoran / kafe|Online işletme|SaaS fikri veya ürünü|Diğer",
    workflowOptions: "Instagram DM|WhatsApp|Telefon aramaları|Web sitesi formu|Google Sheets / Excel|Yüz yüze|Mevcut rezervasyon sistemi|Mevcut CRM|Diğer",
    systemOptions: "Online rezervasyon|Online ödeme|Yönetim paneli|Müşteri paneli|CRM / müşteri yönetimi|Online sipariş|Dosya yükleme|Otomatik SMS ve e-posta|Sipariş veya rezervasyon durumu|Raporlama|Farklı kullanıcı rolleri|AI|Otomasyon|Diğer",
    customerOptions: "Kayıt / giriş|Randevu alma|Ödeme yapma|Durum görüntüleme|Geçmiş işlemleri görme|Dosya yükleme|SMS veya e-posta alma|Dosya indirme|Talep veya not gönderme|Henüz emin değilim",
    adminOptions: "Rezervasyonları görme|Takvimi yönetme|Siparişleri yönetme|Müşterileri yönetme|Ödemeleri yönetme|Durumları değiştirme|Dosya yükleme veya görme|İç notlar|Gelir raporu|Hizmetleri yönetme|Ekip veya rolleri yönetme|Farklı erişim seviyeleri|Henüz emin değilim",
    sensitiveOptions: "Hayır, normal müşteri bilgisi|Evet, müşteri dosyası veya fotoğrafı|Evet, medikal veya hassas bilgi|Emin değilim",
    budgetOptions: "£750 altı|£750 - £1,500|£1,500 - £3,000|£3,000+|Henüz emin değilim",
    timelineOptions: "Mümkün olan en kısa sürede|2-4 hafta|1-2 ay|2 aydan fazla|Henüz emin değilim",
  },
  steps: [
    { title: "Önce işletmenizi anlayalım", helper: "Projeyi doğru değerlendirmek için birkaç temel bilgiye ihtiyacımız var." },
    { title: "İşletmeniz hangi alanda çalışıyor?", helper: "İşinize en yakın seçeneği seçin." },
    { title: "İşler şu anda nasıl yürüyor?", helper: "Müşteriler bugün nasıl iletişime geçiyor, rezervasyon yapıyor veya sipariş veriyor?", question: "Mevcut kanalları veya araçları seçin." },
    { title: "Şu an en büyük problem nedir?", helper: "İlk önce tek bir bölüm iyileşecekse hangisi olurdu?", question: "Ana problemi kendi kelimelerinizle yazın." },
    { title: "Sistem neleri içermeli?", helper: "Sisteminiz için önemli parçaları seçin." },
    { title: "Müşteri sistem içinde ne yapabilmeli?", helper: "Sistem içindeki müşteri deneyimini düşünün." },
    { title: "Yönetim panelinde ekibinizin neye ihtiyacı var?", helper: "Günlük yönetmeniz gereken şeyleri seçin." },
    { title: "Sistem hassas veri veya özel dosya saklayacak mı?", helper: "Bu, erişim, güvenlik ve veri sahipliğini değerlendirmemize yardımcı olur." },
    { title: "Yaklaşık bütçe ve zaman", helper: "İlk değerlendirme için yaklaşık bir aralık yeterli." },
    { title: "Bilmemiz gereken başka bir şey var mı?", helper: "Göndermeden önce ek bağlam ekleyin." },
  ],
  sensitiveHelper: "Hassas veya medikal veri varsa, teklifte güvenlik, erişim seviyeleri ve veri sahipliği ayrıca değerlendirilir.",
});

applyReviewLocale("ru", {
  consent: "Я понимаю, что эта форма нужна для первичной оценки проекта, и если проект подходит, со мной свяжутся для согласования сессии System Review.",
  fields: {
    name: "Ваше имя",
    businessName: "Название бизнеса",
    email: "Рабочий email",
    website: "Сайт или ссылка на Instagram",
    other: "Кратко поясните",
    workflowNotes: "Кратко опишите текущий процесс",
    mainProblem: "Главная проблема",
    sensitiveNotes: "Какие данные или файлы будут храниться?",
    finalNotes: "Что ещё нам нужно знать?",
    budget: "Примерный бюджет",
    timeline: "Желаемые сроки",
  },
  placeholders: {
    name: "например, Сара Иванова",
    businessName: "например, Aura Clinic",
    email: "name@company.com",
    website: "https://... или @yourpage",
    businessOther: "Кратко опишите тип бизнеса",
    workflowNotes: "Достаточно нескольких строк.",
    mainProblem: "Например: бронирования разбросаны, платежи отдельно, клиенты часто спрашивают статус или команда не управляет всем из одной панели.",
    systemOther: "Что ещё должно быть в системе?",
    sensitiveNotes: "Фото клиентов, медицинские заметки, частные файлы, счета или документы.",
    finalNotes: "Добавьте детали об идее, текущих инструментах, файлах или похожих системах.",
  },
  choiceLabels: {
    businessTypes: "Клиника красоты / здоровья|Стоматология / медицинская клиника|Печать и реклама|Салон / ногти / волосы|Коуч / консультант / личные услуги|Магазин / бутик|Ресторан / кафе|Онлайн-бизнес|Идея или продукт SaaS|Другое",
    workflowOptions: "Instagram DM|WhatsApp|Телефонные звонки|Форма на сайте|Google Sheets / Excel|Лично|Текущая система бронирования|Текущая CRM|Другое",
    systemOptions: "Онлайн-бронирование|Онлайн-оплата|Админ-панель|Кабинет клиента|CRM / управление клиентами|Онлайн-заказ|Загрузка файлов|Автоматические SMS и email|Статус заказа или бронирования|Отчёты|Разные роли пользователей|AI|Автоматизация|Другое",
    customerOptions: "Регистрация / вход|Записаться|Оплатить|Посмотреть статус|Посмотреть историю|Загрузить файл|Получить SMS или email|Скачать файл|Отправить запрос или комментарий|Пока не уверен",
    adminOptions: "Видеть бронирования|Управлять расписанием|Управлять заказами|Управлять клиентами|Управлять оплатами|Менять статусы|Загружать или смотреть файлы|Внутренние заметки|Отчёт по доходам|Управлять услугами|Управлять командой или ролями|Разные уровни доступа|Пока не уверен",
    sensitiveOptions: "Нет, обычные данные клиентов|Да, файлы или фото клиентов|Да, медицинские или чувствительные данные|Не уверен",
    budgetOptions: "До £750|£750 - £1,500|£1,500 - £3,000|£3,000+|Пока не уверен",
    timelineOptions: "Как можно скорее|2-4 недели|1-2 месяца|Больше 2 месяцев|Пока не уверен",
  },
  steps: [
    { title: "Сначала познакомимся с вашим бизнесом", helper: "Несколько базовых данных помогут нам правильно оценить проект." },
    { title: "В какой сфере работает ваш бизнес?", helper: "Выберите наиболее близкий вариант." },
    { title: "Как всё работает сейчас?", helper: "Как клиенты связываются, бронируют или делают заказ?", question: "Выберите текущие каналы или инструменты." },
    { title: "Какая проблема самая большая?", helper: "Если улучшать сначала одну часть, что это будет?", question: "Опишите проблему своими словами." },
    { title: "Что должна включать система?", helper: "Выберите важные элементы будущей системы." },
    { title: "Что клиент должен уметь делать в системе?", helper: "Подумайте о клиентском опыте внутри системы." },
    { title: "Что нужно вашей команде в админ-панели?", helper: "Выберите, что нужно управлять каждый день." },
    { title: "Будет ли система хранить чувствительные данные или частные файлы?", helper: "Это важно для доступа, безопасности и владения данными." },
    { title: "Примерный бюджет и сроки", helper: "Для первой оценки достаточно примерного диапазона." },
    { title: "Есть ли ещё что-то важное?", helper: "Добавьте дополнительный контекст перед отправкой." },
  ],
  sensitiveHelper: "Если есть чувствительные или медицинские данные, в предложении отдельно рассмотрим безопасность, уровни доступа и владение данными.",
});

applyReviewLocale("zh", {
  consent: "我了解此表单用于项目初步评估；如果项目合适，我们会联系我安排 System Review 会议。",
  fields: {
    name: "您的姓名",
    businessName: "业务名称",
    email: "工作邮箱",
    website: "当前网站或 Instagram 链接",
    other: "请简要说明",
    workflowNotes: "简要描述当前流程",
    mainProblem: "主要问题",
    sensitiveNotes: "会存储哪些信息或文件？",
    finalNotes: "还有什么需要说明？",
    budget: "大致预算",
    timeline: "期望时间",
  },
  placeholders: {
    name: "例如 Sara Chen",
    businessName: "例如 Aura Clinic",
    email: "name@company.com",
    website: "https://... 或 @yourpage",
    businessOther: "简要说明业务类型",
    workflowNotes: "几句话即可。",
    mainProblem: "例如：预约分散、付款独立、客户频繁询问状态、信息散落在多个工具中，或团队无法用一个后台管理。",
    systemOther: "系统还需要包含什么？",
    sensitiveNotes: "例如客户照片、医疗记录、私人文件、发票或身份证明。",
    finalNotes: "补充关于想法、当前工具、文件、类似系统或希望构建内容的信息。",
  },
  choiceLabels: {
    businessTypes: "美容 / 健康诊所|牙科 / 医疗诊所|印刷与广告|美发 / 美甲 / 沙龙|教练 / 顾问 / 个人服务|商店 / 精品店|餐厅 / 咖啡馆|线上业务|SaaS 想法或产品|其他",
    workflowOptions: "Instagram 私信|WhatsApp|电话|网站表单|Google Sheets / Excel|线下|当前预约系统|当前 CRM|其他",
    systemOptions: "在线预约|在线支付|管理后台|客户面板|CRM / 客户管理|在线下单|文件上传|自动短信和邮件|订单或预约状态|报表|不同用户角色|AI|自动化|其他",
    customerOptions: "注册 / 登录|预约时间|付款|查看状态|查看历史记录|上传文件|接收短信或邮件|下载文件|发送请求或说明|暂时不确定",
    adminOptions: "查看预约|管理日程|管理订单|管理客户|管理付款|更改状态|上传或查看文件|内部备注|收入报表|管理服务|管理员工或角色|不同访问权限|暂时不确定",
    sensitiveOptions: "否，只有普通客户信息|是，会存储客户文件或照片|是，有医疗或敏感信息|不确定",
    budgetOptions: "低于 £750|£750 至 £1,500|£1,500 至 £3,000|£3,000+|暂时不确定",
    timelineOptions: "越快越好|2 至 4 周|1 至 2 个月|超过 2 个月|暂时不确定",
  },
  steps: [
    { title: "先了解您的业务", helper: "我们需要一些基本信息，以便更准确地评估项目。" },
    { title: "您的业务属于哪个领域？", helper: "请选择最接近的选项。" },
    { title: "现在的工作流程是怎样的？", helper: "客户目前如何联系、预约或下单？", question: "请选择当前使用的渠道或工具。" },
    { title: "目前最大的问题是什么？", helper: "如果只优先改善一个环节，会是哪一个？", question: "请用自己的话描述主要问题。" },
    { title: "系统需要包含哪些内容？", helper: "请选择对您的系统重要的部分。" },
    { title: "客户在系统里需要做什么？", helper: "请从客户体验角度考虑。" },
    { title: "团队在管理后台需要什么？", helper: "请选择日常需要管理的内容。" },
    { title: "系统会存储敏感数据或私人文件吗？", helper: "这有助于我们评估权限、安全和数据归属。" },
    { title: "大致预算和时间", helper: "初步评估只需要一个大致范围。" },
    { title: "还有其他需要说明的吗？", helper: "提交前可补充任何背景信息。" },
  ],
  sensitiveHelper: "如果涉及敏感或医疗数据，提案中会单独评估安全、访问权限和数据归属。",
});

applyReviewLocale("ko", {
  consent: "이 양식은 프로젝트 초기 검토를 위한 것이며, 프로젝트가 적합한 경우 System Review 세션 조율을 위해 연락받는다는 점을 이해합니다.",
  fields: {
    name: "이름",
    businessName: "비즈니스 이름",
    email: "업무용 이메일",
    website: "현재 웹사이트 또는 Instagram 링크",
    other: "간단히 설명해주세요",
    workflowNotes: "현재 업무 흐름을 간단히 설명해주세요",
    mainProblem: "가장 큰 문제",
    sensitiveNotes: "어떤 정보나 파일이 저장되나요?",
    finalNotes: "추가로 알려주실 내용이 있나요?",
    budget: "대략적인 예산",
    timeline: "희망 일정",
  },
  placeholders: {
    name: "예: Sara Kim",
    businessName: "예: Aura Clinic",
    email: "name@company.com",
    website: "https://... 또는 @yourpage",
    businessOther: "비즈니스 유형을 간단히 적어주세요",
    workflowNotes: "몇 줄이면 충분합니다.",
    mainProblem: "예: 예약이 흩어져 있음, 결제가 따로 있음, 고객이 상태를 자주 문의함, 정보가 여러 곳에 있음.",
    systemOther: "시스템에 또 무엇이 필요하나요?",
    sensitiveNotes: "고객 사진, 의료 메모, 개인 파일, 청구서 또는 신분 문서 등.",
    finalNotes: "아이디어, 현재 도구, 파일, 유사한 시스템 또는 만들고 싶은 내용을 알려주세요.",
  },
  choiceLabels: {
    businessTypes: "뷰티 / 헬스 클리닉|치과 / 의료 클리닉|인쇄 및 광고|살롱 / 네일 / 헤어|코치 / 컨설턴트 / 개인 서비스|상점 / 부티크|레스토랑 / 카페|온라인 비즈니스|SaaS 아이디어 또는 제품|기타",
    workflowOptions: "Instagram DM|WhatsApp|전화|웹사이트 폼|Google Sheets / Excel|오프라인|현재 예약 시스템|현재 CRM|기타",
    systemOptions: "온라인 예약|온라인 결제|관리자 대시보드|고객 패널|CRM / 고객 관리|온라인 주문|파일 업로드|자동 SMS 및 이메일|주문 또는 예약 상태|리포트|다양한 사용자 역할|AI|자동화|기타",
    customerOptions: "가입 / 로그인|예약하기|결제하기|상태 보기|이전 예약 또는 주문 보기|파일 업로드|SMS 또는 이메일 받기|파일 다운로드|요청 또는 메모 보내기|아직 잘 모르겠음",
    adminOptions: "예약 보기|일정 관리|주문 관리|고객 관리|결제 관리|상태 변경|파일 업로드 또는 보기|내부 메모|수익 리포트|서비스 관리|직원 또는 역할 관리|다른 접근 권한|아직 잘 모르겠음",
    sensitiveOptions: "아니요, 일반 고객 정보만 저장|예, 고객 파일 또는 사진 저장|예, 의료 또는 민감 정보 있음|잘 모르겠음",
    budgetOptions: "£750 미만|£750 - £1,500|£1,500 - £3,000|£3,000+|아직 잘 모르겠음",
    timelineOptions: "가능한 빨리|2-4주|1-2개월|2개월 이상|아직 잘 모르겠음",
  },
  steps: [
    { title: "먼저 비즈니스를 이해하겠습니다", helper: "프로젝트를 제대로 검토하려면 기본 정보가 필요합니다." },
    { title: "어떤 분야의 비즈니스인가요?", helper: "가장 가까운 항목을 선택해주세요." },
    { title: "현재 업무는 어떻게 진행되나요?", helper: "고객은 지금 어떻게 연락하고 예약하거나 주문하나요?", question: "현재 사용하는 채널이나 도구를 선택해주세요." },
    { title: "지금 가장 큰 문제는 무엇인가요?", helper: "먼저 개선해야 할 한 가지가 있다면 무엇인가요?", question: "주요 문제를 직접 설명해주세요." },
    { title: "시스템에 무엇이 필요하나요?", helper: "시스템에 중요한 기능을 선택해주세요." },
    { title: "고객은 시스템 안에서 무엇을 할 수 있어야 하나요?", helper: "고객 경험을 기준으로 생각해주세요." },
    { title: "팀은 관리자 패널에서 무엇이 필요하나요?", helper: "매일 관리해야 하는 항목을 선택해주세요." },
    { title: "민감한 데이터나 개인 파일을 저장하나요?", helper: "접근 권한, 보안, 데이터 소유권 검토에 필요합니다." },
    { title: "대략적인 예산과 일정", helper: "첫 검토에는 대략적인 범위면 충분합니다." },
    { title: "추가로 알려주실 내용이 있나요?", helper: "제출 전에 필요한 맥락을 추가해주세요." },
  ],
  sensitiveHelper: "민감하거나 의료 관련 데이터가 있다면 제안서에서 보안, 접근 권한, 데이터 소유권을 별도로 검토합니다.",
});

applyReviewLocale("ja", {
  consent: "このフォームはプロジェクトの初期確認のためのものであり、適している場合は System Review の日程調整について連絡を受けることを理解しています。",
  fields: {
    name: "お名前",
    businessName: "ビジネス名",
    email: "ビジネス用メール",
    website: "現在のサイトまたは Instagram リンク",
    other: "簡単にご説明ください",
    workflowNotes: "現在の流れを簡単に説明してください",
    mainProblem: "一番大きな課題",
    sensitiveNotes: "どのような情報やファイルを保存しますか？",
    finalNotes: "ほかに伝えておきたいことはありますか？",
    budget: "おおよその予算",
    timeline: "希望時期",
  },
  placeholders: {
    name: "例：Sara Tanaka",
    businessName: "例：Aura Clinic",
    email: "name@company.com",
    website: "https://... または @yourpage",
    businessOther: "ビジネスの種類を簡単にご記入ください",
    workflowNotes: "数行で十分です。",
    mainProblem: "例：予約が分散している、支払いが別管理、顧客から確認が多い、情報が複数の場所にある、チームが一つの管理画面で扱えない。",
    systemOther: "ほかに必要な機能はありますか？",
    sensitiveNotes: "顧客写真、医療メモ、個人ファイル、請求書、本人確認書類など。",
    finalNotes: "アイデア、現在のツール、ファイル、参考システム、作りたい内容を共有してください。",
  },
  choiceLabels: {
    businessTypes: "美容 / ヘルスクリニック|歯科 / 医療クリニック|印刷・広告|サロン / ネイル / ヘア|コーチ / コンサル / 個人サービス|ショップ / ブティック|レストラン / カフェ|オンラインビジネス|SaaS のアイデア・製品|その他",
    workflowOptions: "Instagram DM|WhatsApp|電話|サイトフォーム|Google Sheets / Excel|対面|現在の予約システム|現在の CRM|その他",
    systemOptions: "オンライン予約|オンライン決済|管理ダッシュボード|顧客パネル|CRM / 顧客管理|オンライン注文|ファイルアップロード|自動 SMS・メール|注文または予約ステータス|レポート|複数のユーザー権限|AI|自動化|その他",
    customerOptions: "登録 / ログイン|予約する|支払う|ステータスを見る|過去の予約や注文を見る|ファイルをアップロード|SMS またはメールを受け取る|ファイルをダウンロード|依頼やメモを送る|まだわからない",
    adminOptions: "予約を見る|スケジュール管理|注文管理|顧客管理|支払い管理|ステータス変更|ファイルのアップロード・確認|内部メモ|売上レポート|サービス管理|スタッフや権限管理|異なるアクセス権限|まだわからない",
    sensitiveOptions: "いいえ、通常の顧客情報のみ|はい、顧客ファイルや写真を保存します|はい、医療情報または機密情報があります|わかりません",
    budgetOptions: "£750 未満|£750〜£1,500|£1,500〜£3,000|£3,000以上|まだわからない",
    timelineOptions: "できるだけ早く|2〜4週間|1〜2か月|2か月以上|まだわからない",
  },
  steps: [
    { title: "まずビジネスについて教えてください", helper: "プロジェクトを正しく確認するために、基本情報が必要です。" },
    { title: "どの分野のビジネスですか？", helper: "最も近い選択肢をお選びください。" },
    { title: "現在はどのように運用していますか？", helper: "顧客は今どのように連絡、予約、注文していますか？", question: "現在使っているチャネルやツールを選んでください。" },
    { title: "現在一番大きな課題は何ですか？", helper: "最初に改善するなら、どの部分ですか？", question: "主な課題をあなたの言葉で説明してください。" },
    { title: "システムに必要なものは何ですか？", helper: "重要な機能を選んでください。" },
    { title: "顧客はシステム内で何ができるべきですか？", helper: "顧客体験を考えて選んでください。" },
    { title: "管理画面でチームに必要なものは何ですか？", helper: "日々管理したい項目を選んでください。" },
    { title: "機密データや個人ファイルを保存しますか？", helper: "アクセス権限、セキュリティ、データ所有を確認するために必要です。" },
    { title: "おおよその予算と時期", helper: "初回確認ではおおよその範囲で十分です。" },
    { title: "ほかに伝えておきたいことはありますか？", helper: "送信前に必要な補足を追加してください。" },
  ],
  sensitiveHelper: "機密情報や医療情報がある場合、提案書ではセキュリティ、アクセス権限、データ所有について別途確認します。",
});

applyReviewLocale("hi", {
  consent: "मैं समझता/समझती हूं कि यह फॉर्म प्रोजेक्ट की शुरुआती समीक्षा के लिए है और यदि प्रोजेक्ट उपयुक्त हुआ तो System Review session के लिए मुझसे संपर्क किया जाएगा.",
  fields: {
    name: "आपका नाम",
    businessName: "बिजनेस का नाम",
    email: "कार्य ईमेल",
    website: "मौजूदा वेबसाइट या Instagram लिंक",
    other: "कृपया संक्षेप में बताएं",
    workflowNotes: "मौजूदा प्रक्रिया को संक्षेप में बताएं",
    mainProblem: "मुख्य समस्या",
    sensitiveNotes: "किस प्रकार की जानकारी या फाइलें सेव होंगी?",
    finalNotes: "क्या कुछ और बताना चाहेंगे?",
    budget: "अनुमानित बजट",
    timeline: "अनुमानित समय",
  },
  placeholders: {
    name: "जैसे Sara Sharma",
    businessName: "जैसे Aura Clinic",
    email: "name@company.com",
    website: "https://... या @yourpage",
    businessOther: "बिजनेस का प्रकार संक्षेप में लिखें",
    workflowNotes: "कुछ पंक्तियां काफी हैं।",
    mainProblem: "जैसे बुकिंग बिखरी हुई है, भुगतान अलग है, ग्राहक बार-बार स्थिति पूछते हैं, या टीम एक panel से सब कुछ manage नहीं कर पाती।",
    systemOther: "सिस्टम में और क्या शामिल होना चाहिए?",
    sensitiveNotes: "ग्राहक फोटो, medical notes, private files, invoices या ID documents.",
    finalNotes: "Idea, current tools, files, similar systems या जो बनवाना चाहते हैं उसके बारे में बताएं।",
  },
  choiceLabels: {
    businessTypes: "ब्यूटी / हेल्थ क्लिनिक|डेंटल / मेडिकल क्लिनिक|प्रिंटिंग और विज्ञापन|सैलून / नेल / हेयर|कोच / सलाहकार / व्यक्तिगत सेवा|दुकान / बुटीक|रेस्तरां / कैफे|ऑनलाइन बिजनेस|SaaS आइडिया या प्रोडक्ट|अन्य",
    workflowOptions: "Instagram DM|WhatsApp|फोन कॉल|वेबसाइट फॉर्म|Google Sheets / Excel|व्यक्तिगत रूप से|मौजूदा बुकिंग सिस्टम|मौजूदा CRM|अन्य",
    systemOptions: "ऑनलाइन बुकिंग|ऑनलाइन भुगतान|एडमिन डैशबोर्ड|ग्राहक पैनल|CRM / ग्राहक प्रबंधन|ऑनलाइन ऑर्डर|फाइल अपलोड|ऑटो SMS और ईमेल|ऑर्डर या बुकिंग स्थिति|रिपोर्टिंग|अलग user roles|AI|ऑटोमेशन|अन्य",
    customerOptions: "रजिस्टर / लॉग इन|अपॉइंटमेंट बुक करना|भुगतान करना|स्थिति देखना|पिछली sessions या orders देखना|फाइल अपलोड करना|SMS या ईमेल पाना|फाइल डाउनलोड करना|request या note भेजना|अभी निश्चित नहीं",
    adminOptions: "बुकिंग देखना|शेड्यूल manage करना|ऑर्डर manage करना|ग्राहक manage करना|भुगतान manage करना|status बदलना|फाइल upload या view करना|internal notes|revenue report|services manage करना|staff या roles manage करना|अलग access levels|अभी निश्चित नहीं",
    sensitiveOptions: "नहीं, सामान्य ग्राहक जानकारी ही है|हां, ग्राहक files या photos store होंगे|हां, medical या sensitive जानकारी है|निश्चित नहीं",
    budgetOptions: "£750 से कम|£750 से £1,500|£1,500 से £3,000|£3,000+|अभी निश्चित नहीं",
    timelineOptions: "जितना जल्दी हो सके|2 से 4 सप्ताह|1 से 2 महीने|2 महीने से ज्यादा|अभी निश्चित नहीं",
  },
  steps: [
    { title: "पहले आपके बिजनेस को समझते हैं", helper: "प्रोजेक्ट को सही तरह से समझने के लिए कुछ basic जानकारी चाहिए." },
    { title: "आपका बिजनेस किस क्षेत्र में है?", helper: "सबसे नज़दीकी विकल्प चुनें." },
    { title: "अभी काम कैसे होता है?", helper: "ग्राहक अभी कैसे संपर्क, booking या order करते हैं?", question: "वर्तमान channels या tools चुनें." },
    { title: "अभी सबसे बड़ी समस्या क्या है?", helper: "अगर एक चीज़ पहले बेहतर करनी हो, तो वह क्या होगी?", question: "मुख्य समस्या अपने शब्दों में लिखें." },
    { title: "सिस्टम में क्या शामिल होना चाहिए?", helper: "अपने सिस्टम के लिए जरूरी भाग चुनें." },
    { title: "ग्राहक सिस्टम में क्या कर सके?", helper: "ग्राहक अनुभव को ध्यान में रखें." },
    { title: "आपकी टीम को admin panel में क्या चाहिए?", helper: "जो चीजें रोज manage करनी हैं उन्हें चुनें." },
    { title: "क्या सिस्टम sensitive data या private files store करेगा?", helper: "इससे access, security और data ownership समझने में मदद मिलती है." },
    { title: "अनुमानित budget और timeline", helper: "पहली review के लिए rough range काफी है." },
    { title: "क्या कुछ और बताना चाहेंगे?", helper: "भेजने से पहले कोई जरूरी context जोड़ें." },
  ],
  sensitiveHelper: "यदि sensitive या medical data है, तो proposal में security, access levels और data ownership अलग से review होंगे.",
});

export const getSystemReviewCopy = (language?: string) => {
  const normalized = String(language || "en").split("-")[0].toLowerCase();
  return systemReviewCopy[normalized] || systemReviewCopy[aliasMap[normalized]] || systemReviewCopy.en;
};
